{
  "ruby.lint": {
    "rubocop": true
  },
  "ruby.format": "rubocop",
  "editor.formatOnSave": true,
  "solargraph.useBundler": true,
  "solargraph.diagnostics": true,
  "solargraph.formatting": true
}
