
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: onegrab_development

test:
  <<: *default
  database: onegrab_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    prepared_statements: false
  cache:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
    database: onegrab_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
    database: onegrab_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
    database: onegrab_production_cable
    migrations_paths: db/cable_migrate
