
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: onegrab_development

test:
  <<: *default
  database: onegrab_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    prepared_statements: false
  queue:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
  cable:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
    url: <%= ENV['DATABASE_URL'] %>
